config/routes.rb
Rails.application.routes.draw do

  resources :photos

  resources :settings

  resources :galleries

  resources :posts

  resources :gcm_registrations

  resources :users

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  root 'welcome#index'

  get 'api/news' => 'api#news_feed'
  get 'api/zones' => 'api#zones'
  get 'api/editions' => 'api#editions'
  get 'api/push' => 'api#gcm_push'
  post 'api/save_gcm_registration' => 'api#save_gcm_registration'

end

app/models/gcm_registration.rb
class GcmRegistration < ActiveRecord::Base
end

app/controllers/gcm_registrations_controller.rb
class GcmRegistrationsController < ApplicationController
  before_action :set_gcm_registration, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @gcm_registrations = GcmRegistration.all
    respond_with(@gcm_registrations)
  end

  def show
    respond_with(@gcm_registration)
  end

  def new
    @gcm_registration = GcmRegistration.new
    respond_with(@gcm_registration)
  end

  def edit
  end

  def create
    @gcm_registration = GcmRegistration.new(gcm_registration_params)
    @gcm_registration.save
    respond_with(@gcm_registration)
  end

  def update
    @gcm_registration.update(gcm_registration_params)
    respond_with(@gcm_registration)
  end

  def destroy
    @gcm_registration.destroy
    respond_with(@gcm_registration)
  end

  private
    def set_gcm_registration
      @gcm_registration = GcmRegistration.find(params[:id])
    end

    def gcm_registration_params
      params.require(:gcm_registration).permit(:user_id, :gcm_registration_id)
    end
end

app/helpers/gcm_registrations_helper.rb
module GcmRegistrationsHelper
end

app/views/gcm_registrations/_form.html.erb
<%= form_for(@gcm_registration) do |f| %>
  <% if @gcm_registration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gcm_registration.errors.count, "error") %> prohibited this gcm_registration from being saved:</h2>

      <ul>
      <% @gcm_registration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :gcm_registration_id %><br>
    <%= f.text_field :gcm_registration_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gcm_registrations/edit.html.erb
<h1>Editing gcm_registration</h1>

<%= render 'form' %>

<%= link_to 'Show', @gcm_registration %> |
<%= link_to 'Back', gcm_registrations_path %>

app/views/gcm_registrations/index.html.erb
<h1>Listing gcm_registrations</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Gcm registration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gcm_registrations.each do |gcm_registration| %>
      <tr>
        <td><%= gcm_registration.user_id %></td>
        <td><%= gcm_registration.gcm_registration_id %></td>
        <td><%= link_to 'Show', gcm_registration %></td>
        <td><%= link_to 'Edit', edit_gcm_registration_path(gcm_registration) %></td>
        <td><%= link_to 'Destroy', gcm_registration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gcm registration', new_gcm_registration_path %>

app/views/gcm_registrations/new.html.erb
<h1>New gcm_registration</h1>

<%= render 'form' %>

<%= link_to 'Back', gcm_registrations_path %>

app/views/gcm_registrations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @gcm_registration.user_id %>
</p>

<p>
  <strong>Gcm registration:</strong>
  <%= @gcm_registration.gcm_registration_id %>
</p>

<%= link_to 'Edit', edit_gcm_registration_path(@gcm_registration) %> |
<%= link_to 'Back', gcm_registrations_path %>